In [2]:
import pandas as pd
import numpy as np


df= pd.read_csv("https://raw.githubusercontent.com/mikeizbicki/datasets/master/csv/uci/house-votes-84.data", header=None)
df.head()

           0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
0  republican  n  y  n  y  y  y  n  n  n  y  ?  y  y  y  n  y
1  republican  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  ?
2    democrat  ?  y  y  ?  y  y  n  n  n  n  y  n  y  y  n  n
3    democrat  n  y  y  n  ?  y  n  n  n  n  y  n  y  n  n  y
4    democrat  y  y  y  n  y  y  n  n  n  n  y  ?  y  y  y  y

In [ ]:
df.describe()

In [ ]:
df.info()

In [ ]:
new_df={"republican":0,"democrat":1}
df[0]= df[0].apply(lambda x: new_df[x])

In [ ]:
df.head()

In [ ]:
new_df={"y":1, "n":0,'?':'?'}
for column in df.columns.drop(0):
 df[column]= df[column].apply(lambda x: new_df[x])
df.head()

In [ ]:
for column in df.columns:
    df[column].replace(['?'],df[column].mode()[0], inplace=True)
df.head()

In [ ]:
y=df[0]
X=df.iloc[:,1:]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn import tree
import numpy as np
import matplotlib.pyplot as plt

test=[0.5, 0.4, 0.3, 0.2]
train=[0.5,0.6,0.7,0.8]
rand=[1,2,3,4,5]

for i in test:
    min_accuracy=1
    max_accuracy=0
    min_ts=10000000
    max_ts=0
    total_accuracy=0
    total_size=0
    
    print('_________________',100*(1-i),'%____________________\n')
    for j in range(5):
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=i, random_state=rand[j])
        model = DecisionTreeClassifier()
        model = model.fit(X_train, y_train)
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)
        train_accuracy = accuracy_score(y_train, y_train_pred)
        test_accuracy = accuracy_score(y_test, y_test_pred)
    
        tree_size=model.tree_.node_count
    
        print('The training accuracy of', j+1,'=', test_accuracy)
        print('The tree size of iteration no.', j+1,'=', tree_size)
    
        if (test_accuracy<min_accuracy):
            min_accuracy=test_accuracy
        if (test_accuracy>max_accuracy):
            max_accuracy=test_accuracy
        if (tree_size<min_ts):
            min_ts=tree_size
        if(tree_size>max_ts):
            max_ts=tree_size
        total_accuracy+=test_accuracy
        total_size+=tree_size
        print('minimum accuracy of training set: ',min_accuracy)
        print('maximum accuracy of training set: ',max_accuracy)
        print('mean accuracy of training set: ',(total_accuracy/5))
        
    
    
        print('minimum tree size: ',min_ts )
        print('maximum tree size: ',max_ts )
        print('mean tree size: ',(tree_size/5))

In [ ]:
print('----accuracy plot-----')
plt.bar(train, (test_accuracy/5), color ='maroon',width = 0.4)
plt.show()
print('----tree size plot-----')
plt.bar(train, (tree_size/5), color ='maroon',width = 0.4)
plt.show()